sudo: false
matrix:
  fast_finish: true
  include:
  - python: 3.5.3
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
    sudo: true
cache:
  directories:
  - "$HOME/.cache/pip"
language: python
install: pip install -U tox-travis
script: travis_wait 30 tox --develop
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: awarecan
  password:
    secure: Y8SJk0cu382IbhkOrlD0XYssRUuwhimCne7+ZNy2Wv6Q58acXkv7Ts64KeiqWvR2gzGbJRn9UXOF2vD10HDSFfxqZqnhlxYjdnlnuJUAE/IB7502txKMvSkhessnZTa3nE1OX8wKVsQwbS+LM+L65I8EF3kohL94j8uqlzFzq3TW5A9mKsyGUXi1PpIpX7HMxp5ZZOLs7kkymNWRAhrDnGd0xmVBtyiVOlquUGLUDGvvnxbVzwM6JIJOy/a117KzPFFaKCn75PW7Qf1B+qKKQRPJRoASw0VBDJ8ljAO+Z8d4G6zhXwBGqNg+Mrz1a+ouveFrJXQE5XRtdo5766E82j81E3/xFmq7XlXSVy0xkDMo97ma8bOt4/gKllRGKQPdwLL54Bf0P/qLYJoRUpyjNkW+Kgkqser1teJgk1ibOBgbCiye4ty/Cn+l5FQ9oF6xxY5DF/jLoz/mMGIjiyOi8Ht1T9ZOaRrhCQLMw9tjHZBtXGkPx8BY6kUXE0ER7VDOABX36FDf+avpIwlaxn6NjdgFQVPQYzdzV6nQOErZfEkwBaRPltlf+fJ4yb/Kih0My546ldQgdhA+/0btOPkXNKStzJY36EtAgQ2bU7LDLPsCVdwvWUajJ2i4qZDCpJPItXJAnsDha99IpLUJLmi01HMiu/Haau+6RByqoVmXi1Y=
  on:
    tags: true
    repo: rtfol/aionest
    python: 3.6
